[build]
output = "build"

[[template]]
input = "**/door.template.json"
output = "{{variant}}.json"
values = [
	{ variant = "iron_door" },
	{ variant = "oak_door" },
	{ variant = "spruce_door" },
	{ variant = "birch_door" },
	{ variant = "jungle_door" },
	{ variant = "acacia_door" },
	{ variant = "dark_oak_door" },
	{ variant = "crimson_door" },
	{ variant = "warped_door" },
]

[[template]]
input = "**/*.template"
output = "../{{variant}}/{{filestem}}.mcfunction"
values = [
	{ variant = "iron_door" },
	{ variant = "oak_door" },
	{ variant = "spruce_door" },
	{ variant = "birch_door" },
	{ variant = "jungle_door" },
	{ variant = "acacia_door" },
	{ variant = "dark_oak_door" },
	{ variant = "crimson_door" },
	{ variant = "warped_door" },
]

[[template]]
input = "**/event/*.template2" # Depth two template
output = "../../{{variant}}/event/{{filestem}}.mcfunction"
values = [
	{ variant = "iron_door" },
	{ variant = "oak_door" },
	{ variant = "spruce_door" },
	{ variant = "birch_door" },
	{ variant = "jungle_door" },
	{ variant = "acacia_door" },
	{ variant = "dark_oak_door" },
	{ variant = "crimson_door" },
	{ variant = "warped_door" },
]

[[template]]
input = "**/method/*.template2" # Depth two template
output = "../../{{variant}}/method/{{filestem}}.mcfunction"
values = [
	{ variant = "iron_door" },
	{ variant = "oak_door" },
	{ variant = "spruce_door" },
	{ variant = "birch_door" },
	{ variant = "jungle_door" },
	{ variant = "acacia_door" },
	{ variant = "dark_oak_door" },
	{ variant = "crimson_door" },
	{ variant = "warped_door" },
]

[[template]]
input = "**/spawn/*.template2" # Depth two template
output = "../../{{variant}}/spawn/{{filestem}}.mcfunction"
values = [
	{ variant = "iron_door" },
	{ variant = "oak_door" },
	{ variant = "spruce_door" },
	{ variant = "birch_door" },
	{ variant = "jungle_door" },
	{ variant = "acacia_door" },
	{ variant = "dark_oak_door" },
	{ variant = "crimson_door" },
	{ variant = "warped_door" },
]
